### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by heesoo-kim97** [heesoo-kim97/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML file and skeleton
- [x] Add image to the HTML
- [x] Create Css file
- [x] Make sure everything is linked properly to HTML
- [x] add image of the car
- [x] Define class for the image and set width
