### ISSUE TITLE
User-can-turn-their-car

### ISSUE THREAD

**Issue by heesoo-kim97** [heesoo-kim97/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create main.js file
- [x] source link the js file to HTML
- [x] Define classes for each rotation of the car in css
       - [ ] Add transform to rotate the cars on right class
- [x] Define a variable that selects image
- [x] add Eventlistener with keyword keydown
- [x] Define a function that if arrow is pointing certain direction it will process the appropriate rotation and action.
